version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
    - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
    restart: always
  mongodb: 
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
      - MONGODB_DATABASE=gugol_dogs